# Generated by Django 4.1.2 on 2024-02-14 04:19

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_es', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('images', models.ImageField(upload_to='')),
                ('info', ckeditor.fields.RichTextField()),
                ('info_es', ckeditor.fields.RichTextField(null=True)),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='journals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'docx', 'rtf'])])),
                ('images', models.ImageField(upload_to='')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSendJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('body', ckeditor.fields.RichTextField()),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_art', models.CharField(max_length=255)),
                ('abstract', models.TextField(help_text='Annotatsiya')),
                ('Keywords', models.TextField(help_text='Kalit sozlar')),
                ('type_art', models.CharField(choices=[('maqola', 'Maqola'), ('tezis', 'Tezis')], default='maqola', max_length=50)),
                ('author_1', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth1', models.TextField(blank=True, null=True)),
                ('author_2', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth2', models.TextField(blank=True, null=True)),
                ('author_3', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth3', models.TextField(blank=True, null=True)),
                ('author_4', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth4', models.TextField(blank=True, null=True)),
                ('create_data', models.DateField()),
                ('firs_page', models.IntegerField(help_text='Birinchis sahifa')),
                ('last_page', models.IntegerField(help_text='Oxirgi sahifa')),
                ('count_page', models.IntegerField(help_text='Maqola sahifalar soni')),
                ('file_articles', models.FileField(upload_to='Articles/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'docx', 'rtf'])])),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journal')),
            ],
        ),
    ]
