# Generated by Django 4.1.2 on 2024-02-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalcategory',
            old_name='info_es',
            new_name='info_en',
        ),
        migrations.RenameField(
            model_name='journalcategory',
            old_name='name_es',
            new_name='name_en',
        ),
    ]
