# Generated by Django 4.1.5 on 2023-01-14 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='upload_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='file',
            field=models.FileField(upload_to='journals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf'])]),
        ),
    ]
