# Generated by Django 4.1.2 on 2024-02-14 04:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_info_es_journalcategory_info_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosendjournal',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='infosendjournal',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='infosendjournal',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='infosendjournal',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='infosendjournal',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='infosendjournal',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
