# Generated by Django 4.1.2 on 2024-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_infosendjournal_body_en_infosendjournal_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Keywords_en',
            field=models.TextField(help_text='Kalit sozlar', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='Keywords_ru',
            field=models.TextField(help_text='Kalit sozlar', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='Keywords_uz',
            field=models.TextField(help_text='Kalit sozlar', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='abstract_en',
            field=models.TextField(help_text='Annotatsiya', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='abstract_ru',
            field=models.TextField(help_text='Annotatsiya', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='abstract_uz',
            field=models.TextField(help_text='Annotatsiya', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_1_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_1_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_2_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_2_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_3_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_3_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_3_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_4_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_4_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='author_4_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth3_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth3_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth3_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth4_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth4_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='info_auth4_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_art_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_art_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_art_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
