# Generated by Django 4.1.5 on 2023-01-16 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_journal_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='file',
            field=models.FileField(upload_to='journals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'docx', 'rtf'])]),
        ),
    ]
