# Generated by Django 4.1.5 on 2023-01-16 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_journal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
