# Generated by Django 4.1.5 on 2023-01-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_journal_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSendJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('body', models.TextField()),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journalcategory')),
            ],
        ),
    ]
