# Generated by Django 4.1.5 on 2023-11-08 04:57

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_infosendjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosendjournal',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='journalcategory',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_art', models.CharField(max_length=255)),
                ('abstract', models.TextField(help_text='Annotatsiya')),
                ('Keywords', models.TextField(help_text='Kalit sozlar')),
                ('type_art', models.CharField(choices=[('maqola', 'Maqola'), ('tezis', 'Tezis')], default='maqola', max_length=50)),
                ('author_1', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth1', models.TextField(blank=True, null=True)),
                ('author_2', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth2', models.TextField(blank=True, null=True)),
                ('author_3', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth3', models.TextField(blank=True, null=True)),
                ('author_4', models.CharField(blank=True, max_length=255, null=True)),
                ('info_auth4', models.TextField(blank=True, null=True)),
                ('create_data', models.DateField()),
                ('firs_page', models.IntegerField(help_text='Birinchis sahifa')),
                ('last_page', models.IntegerField(help_text='Oxirgi sahifa')),
                ('count_page', models.IntegerField(help_text='Maqola sahifalar soni')),
                ('file_articles', models.FileField(upload_to='Articles/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'docx', 'rtf'])])),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.journal')),
            ],
        ),
    ]
